---
title: "Marathon Training Plan Data Cleaning"
author: "Steve Newns"
date: "February 21, 2017"
output:
  github_document: default
  html_document: default
  word_document: default
---

# *Initial Data Inspection*

## Strava Data File

load in the CSV file containing the Strava data file created by and downloaded from **VeloViewer.com** and check out the dataset.

```{r load dataset}
runs <- read.csv("cleanedMarathonTrainingData.csv")
str(runs)
```

#remove 1st col
```{r remove 1st col }
runs$X <- NULL
str(runs)
```

#put month name labels to monthNum to display names in numerical in order
```{r fix monthNum}
runs$monthNum <- factor(runs$monthNum,labels = unique(runs$Month[order(runs$monthNum)]))
```


#load ggplot2
```{r plotting}
library(ggplot2)

#distance histogram
ggplot(data = runs, aes(x = Distance)) + 
  geom_histogram(binwidth = 2, aes(fill = ..count..)) + 
  xlab("Distance (mi)") + 
  ylab("Frequency") + 
  ggtitle("Distribution of Miles Ran in All Runs") + 
  labs(caption="*Majority of runs were between 9 and 11 miles, with a suprisingly low number of runs between 7 and 9 miles")
```


```{r miles by month} 
ggplot(data = runs, aes(x = monthNum, y = Distance, fill = Month)) + 
  geom_bar(stat="identity") +
  xlab("Month") + 
  ylab("Total Miles") + 
  coord_flip() + 
  #geom_text(vjust=0, colour="red") +
  ggtitle("Sum of Miles by Month") + 
  labs(caption="*The largest number of miles ran, 308 miles, was in September")
```

```{r cadence by month} 
ggplot(data = runs, aes(monthNum, Cad)) + 
  geom_boxplot(aes(fill = factor(runs$Month, levels = runs$Month[order(runs$monthNum)], ordered = TRUE)), 
               outlier.colour = "red") + #geom_jitter()
  xlab("Month") + 
  ylab("Cadence") + 
  ggtitle("Cadence per Month") + 
  labs(caption="*Cadence generally increases month over month, due to more workouts, or improved form?")
```

```{r HR over time} 
ggplot(data = runs, aes(x = Date, y = Avg.HR)) + 
  geom_line(aes(group=1)) +
  theme(axis.text.x = element_text(size=0, angle=45)) +
  xlab("Time") + 
  ylab("Average Heart Rate") + 
  ggtitle("Average Heart Rate Over Time") + 
  labs(caption="*Looks like a very slight general decrease, with an outlier of about 100 in the 1st third of the plan
      and 70 in the last 3rd of the plan")
 
```
  
  